###
POST http://localhost:8080/seller/product/register
Content-Type: application/json

{
  "product_name": "빨미까레",
  "price": 3000,
  "detail": "올리브영이랑 아우어베이커리"
}

###
POST http://localhost:8080/member/login
Content-Type: application/json

{
  "username" : "yestruly12",
  "password" : "asdf1234~!"
}


###
POST http://localhost:8080/member/signup/seller
Content-Type: application/json

{
  "username": "yestruly12",
  "password": "asdf1234~!",
  "email": "yestruly@naver.com",
  "phone": "010-1111-1111",
  "address": "서울"
}


###
POST http://localhost:8080/member/signup/customer
Content-Type: application/json

{
  "username": "yestruly",
  "password": "asdf1234~!",
  "email": "yestruly@naver.com",
  "phone": "010-1111-1111",
  "address": "서울"
}



